# Generated by Django 5.0.3 on 2024-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_fooditem_food_title_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
